import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Download, FileText, History, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Reports() {
  const [workspaceId, setWorkspaceId] = useState<number | null>(null);
  const workspaces = trpc.assessment.workspaces.useQuery();
  const jobs = trpc.assessment.jobs.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const findings = trpc.assessment.findings.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const reportJson = trpc.assessment.report.useQuery({ workspaceId: workspaceId ?? 0, format: "json" }, { enabled: Boolean(workspaceId) });
  const reportHtml = trpc.assessment.report.useQuery({ workspaceId: workspaceId ?? 0, format: "html" }, { enabled: Boolean(workspaceId) });
  useEffect(() => { if (!workspaceId && workspaces.data?.[0]) setWorkspaceId(workspaces.data[0].id); }, [workspaceId, workspaces.data]);
  const download = (content: string | undefined, filename: string, type: string) => { if (!content) return; const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); toast.success("Laporan berhasil disiapkan."); };
  return <div className="space-y-6 text-zinc-100"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-red-200">Pusat laporan</p><h1 className="mt-2 text-3xl font-semibold">Laporan siap dibaca.</h1><p className="mt-2 text-sm text-zinc-500">Ekspor ringkasan workspace dan temuan dengan evidence tersanitasi.</p></div><Select value={workspaceId ? String(workspaceId) : undefined} onValueChange={(value) => setWorkspaceId(Number(value))}><SelectTrigger className="w-full border-white/10 bg-white/5 md:w-64"><SelectValue placeholder="Pilih ruang kerja" /></SelectTrigger><SelectContent>{workspaces.data?.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-4 md:grid-cols-3"><Card className="border-white/10 bg-white/[0.035]"><CardContent className="p-5"><FileText className="h-5 w-5 text-red-300" /><p className="mt-4 text-3xl font-semibold">{findings.data?.length ?? 0}</p><p className="text-sm text-zinc-500">Temuan tercatat</p></CardContent></Card><Card className="border-white/10 bg-white/[0.035]"><CardContent className="p-5"><History className="h-5 w-5 text-sky-300" /><p className="mt-4 text-3xl font-semibold">{jobs.data?.length ?? 0}</p><p className="text-sm text-zinc-500">Riwayat pekerjaan</p></CardContent></Card><Card className="border-white/10 bg-white/[0.035]"><CardContent className="p-5"><ShieldCheck className="h-5 w-5 text-emerald-300" /><p className="mt-4 text-3xl font-semibold">100%</p><p className="text-sm text-zinc-500">Evidence tersanitasi</p></CardContent></Card></div><Card className="border-white/10 bg-white/[0.035]"><CardHeader><CardTitle>Ekspor laporan</CardTitle></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row"><Button disabled={!reportJson.data} onClick={() => download(reportJson.data?.content, reportJson.data?.filename ?? "laporan.json", "application/json")} className="bg-red-600 hover:bg-red-500"><Download className="mr-2 h-4 w-4" /> Unduh JSON</Button><Button variant="outline" disabled={!reportHtml.data} onClick={() => download(reportHtml.data?.content, reportHtml.data?.filename ?? "laporan.html", "text/html")} className="border-white/15 bg-white/5 hover:bg-white/10"><Download className="mr-2 h-4 w-4" /> Unduh HTML</Button><Badge variant="outline" className="w-fit self-center border-amber-300/20 text-amber-200">Validasi manual tetap wajib</Badge></CardContent></Card></div>;
}
