import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, FileKey2, Plus, ShieldCheck, Target } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

export default function Workspace() {
  const [, setLocation] = useLocation();
  const [workspaceId, setWorkspaceId] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [target, setTarget] = useState("");
  const [targetType, setTargetType] = useState<"domain" | "url" | "ip" | "cidr">("domain");
  const [evidenceUrl, setEvidenceUrl] = useState("");
  const workspaces = trpc.assessment.workspaces.useQuery();
  const targets = trpc.assessment.targets.useQuery({ workspaceId: workspaceId ?? 0 }, { enabled: Boolean(workspaceId) });
  const createWorkspace = trpc.assessment.createWorkspace.useMutation({ onSuccess: (created) => { if (created?.id) { setWorkspaceId(created.id); toast.success("Ruang kerja berhasil dibuat."); workspaces.refetch(); } }, onError: (error) => toast.error(error.message) });
  const addTarget = trpc.assessment.addTarget.useMutation({ onSuccess: () => { setTarget(""); targets.refetch(); toast.success("Target masuk daftar izin."); }, onError: (error) => toast.error(error.message) });
  const confirmAuthorization = trpc.assessment.confirmAuthorization.useMutation({ onSuccess: () => { toast.success("Otorisasi dikonfirmasi. Pratinjau pipeline sekarang tersedia."); workspaces.refetch(); }, onError: (error) => toast.error(error.message) });
  const uploadEvidence = trpc.assessment.uploadAuthorizationEvidence.useMutation({ onSuccess: (result) => { if (result?.url) setEvidenceUrl(result.url); toast.success("Bukti otorisasi tersimpan dengan aman."); }, onError: (error) => toast.error(error.message) });
  const handleEvidenceUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !workspaceId) return; const reader = new FileReader(); reader.onload = () => { const value = String(reader.result); uploadEvidence.mutate({ workspaceId, filename: file.name, mimeType: file.type as "application/pdf" | "image/png" | "image/jpeg" | "text/plain", base64: value.includes(",") ? value.split(",")[1] ?? "" : value }); }; reader.readAsDataURL(file); };
  const selectedWorkspace = workspaces.data?.find((item) => item.id === workspaceId);

  useEffect(() => { if (!workspaceId && workspaces.data?.[0]) setWorkspaceId(workspaces.data[0].id); }, [workspaceId, workspaces.data]);

  return <div className="space-y-6 text-zinc-100">
    <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-red-200">Kontrol ruang kerja</p><h1 className="mt-2 text-3xl font-semibold">Siapkan penilaian dengan tertib.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Buat ruang kerja, masukkan target yang diizinkan, lalu konfirmasi bukti otorisasi sebelum pipeline dapat dipratinjau.</p></div><Badge variant="outline" className="w-fit border-white/15 bg-white/5 text-zinc-300"><ShieldCheck className="mr-2 h-3 w-3 text-emerald-300" /> Pengamanan scope aktif</Badge></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_1fr]">
      <Card className="border-white/10 bg-white/[0.035]"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Plus className="h-5 w-5 text-red-300" /> Ruang kerja baru</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="workspace-name">Nama ruang kerja</Label><Input id="workspace-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Contoh: Portal Penilaian Q3" className="border-white/10 bg-black/20" /></div><div className="space-y-2"><Label htmlFor="workspace-description">Deskripsi</Label><Textarea id="workspace-description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Tujuan dan batasan penilaian..." className="min-h-24 border-white/10 bg-black/20" /></div><Button disabled={createWorkspace.isPending || name.trim().length < 3} onClick={() => createWorkspace.mutate({ name, description })} className="bg-red-600 hover:bg-red-500">{createWorkspace.isPending ? "Menyimpan..." : "Buat ruang kerja"}<ArrowRight className="ml-2 h-4 w-4" /></Button></CardContent></Card>
      <Card className="border-white/10 bg-white/[0.035]"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Target className="h-5 w-5 text-sky-300" /> Target daftar izin</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Ruang kerja aktif</Label><Select value={workspaceId ? String(workspaceId) : undefined} onValueChange={(value) => setWorkspaceId(Number(value))}><SelectTrigger className="border-white/10 bg-black/20"><SelectValue placeholder="Pilih ruang kerja" /></SelectTrigger><SelectContent>{workspaces.data?.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-3 sm:grid-cols-[1fr_130px]"><div className="space-y-2"><Label htmlFor="target-value">Target</Label><Input id="target-value" value={target} onChange={(event) => setTarget(event.target.value)} placeholder="example.com" className="border-white/10 bg-black/20" /></div><div className="space-y-2"><Label>Jenis</Label><Select value={targetType} onValueChange={(value) => setTargetType(value as typeof targetType)}><SelectTrigger className="border-white/10 bg-black/20"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="domain">Domain</SelectItem><SelectItem value="url">URL</SelectItem><SelectItem value="ip">IP</SelectItem><SelectItem value="cidr">CIDR</SelectItem></SelectContent></Select></div></div><Button variant="outline" disabled={!workspaceId || !target.trim() || addTarget.isPending} onClick={() => workspaceId && addTarget.mutate({ workspaceId, value: target, targetType })} className="border-white/15 bg-white/5 hover:bg-white/10"><Plus className="mr-2 h-4 w-4" /> Tambah ke scope</Button><div className="space-y-2 rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-xs uppercase tracking-[0.18em] text-zinc-500">Daftar izin saat ini</p>{targets.data?.length ? targets.data.map((item) => <div key={item.id} className="flex items-center justify-between border-b border-white/5 py-2 last:border-0"><span className="text-sm">{item.value}</span><Badge variant="outline" className="border-emerald-300/20 text-emerald-300">{item.targetType}</Badge></div>) : <p className="py-2 text-sm text-zinc-500">Belum ada target yang ditambahkan.</p>}</div></CardContent></Card>
    </div>
    <Card className="border-red-300/15 bg-gradient-to-r from-red-500/[0.08] to-transparent"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileKey2 className="h-5 w-5 text-red-300" /> Gate otorisasi</CardTitle></CardHeader><CardContent><div className="grid gap-5 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="text-sm leading-6 text-zinc-400">Konfirmasi bahwa seluruh target dimiliki atau telah mendapat izin tertulis. Bukti dapat diunggah ke storage terproteksi atau direferensikan melalui URL audit internal.</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-zinc-500"><span className="rounded-full border border-white/10 px-3 py-1">Batas laju rendah</span><span className="rounded-full border border-white/10 px-3 py-1">Batas waktu aktif</span><span className="rounded-full border border-white/10 px-3 py-1">Tanpa eksploitasi</span></div></div><div className="space-y-3"><Input type="file" accept="application/pdf,image/png,image/jpeg,text/plain" onChange={handleEvidenceUpload} disabled={!workspaceId || uploadEvidence.isPending} className="border-white/10 bg-black/20 file:mr-3 file:rounded-md file:border-0 file:bg-red-500/20 file:px-3 file:py-1 file:text-xs file:text-red-200" /><Input value={evidenceUrl} onChange={(event) => setEvidenceUrl(event.target.value)} placeholder="https://bukti-izin.internal/..." className="border-white/10 bg-black/20" /><Button disabled={!selectedWorkspace || !targets.data?.length || Boolean(selectedWorkspace.authorizationConfirmed) || confirmAuthorization.isPending} onClick={() => workspaceId && confirmAuthorization.mutate({ workspaceId, evidenceUrl: evidenceUrl || undefined })} className="w-full bg-red-600 hover:bg-red-500">{selectedWorkspace?.authorizationConfirmed ? <><CheckCircle2 className="mr-2 h-4 w-4" /> Otorisasi terkonfirmasi</> : "Konfirmasi otorisasi"}</Button></div></div></CardContent></Card>
  </div>;
}
