import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, Loader2, Sparkles, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const tone: Record<string, string> = { critical: "border-red-300/30 bg-red-400/10 text-red-200", high: "border-orange-300/30 bg-orange-400/10 text-orange-200", medium: "border-amber-300/30 bg-amber-400/10 text-amber-200", low: "border-sky-300/30 bg-sky-400/10 text-sky-200", info: "border-white/15 bg-white/5 text-zinc-300" };
const label: Record<string, string> = { critical: "Kritis", high: "Tinggi", medium: "Sedang", low: "Rendah", info: "Informasi" };
type AiInsightView = { summary: string; priorities: Array<{ title: string; severity: string; rationale: string; confidence: string; remediation: string }>; caveat: string };

export default function AiInsightPanel({ workspaceId }: { workspaceId: number | null }) {
  const [focus, setFocus] = useState("Prioritas review defensif");
  const [insight, setInsight] = useState<AiInsightView | null>(null);
  const analyze = trpc.assessment.aiInsight.useMutation({ onSuccess: setInsight, onError: (error) => toast.error(error.message) });
  return <Card className="border-violet-300/15 bg-gradient-to-br from-violet-500/[0.10] to-white/[0.03]"><CardHeader><CardTitle className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-violet-300" /> Insight AI defensif <Badge variant="outline" className="ml-auto border-violet-300/25 text-violet-200">Server-side</Badge></CardTitle><p className="text-sm text-zinc-400">AI membantu triase observasi tersanitasi. Hasil bukan bukti kerentanan dan tetap memerlukan validasi operator.</p></CardHeader><CardContent className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row"><Textarea value={focus} onChange={(event) => setFocus(event.target.value.slice(0, 240))} placeholder="Fokus analisis, misalnya prioritas hardening header" className="min-h-20 border-white/10 bg-black/20" /><Button onClick={() => { if (!workspaceId) return toast.error("Pilih ruang kerja terlebih dahulu."); analyze.mutate({ workspaceId, focus }); }} disabled={!workspaceId || analyze.isPending} className="h-auto min-h-20 shrink-0 bg-violet-700 hover:bg-violet-600 sm:w-44">{analyze.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Menganalisis…</> : <><WandSparkles className="mr-2 h-4 w-4" /> Analisis aman</>}</Button></div>{insight ? <div className="space-y-4 rounded-xl border border-violet-300/15 bg-black/20 p-4"><div><p className="text-xs uppercase tracking-wider text-violet-200">Ringkasan AI</p><p className="mt-2 text-sm leading-6 text-zinc-300">{insight.summary}</p></div>{insight.priorities.length > 0 && <div className="space-y-2"><p className="text-xs uppercase tracking-wider text-zinc-600">Prioritas review</p>{insight.priorities.map((item, index) => <div key={`${item.title}-${index}`} className="rounded-xl border border-white/10 p-3"><div className="flex flex-wrap items-center gap-2"><Badge className={tone[item.severity] ?? tone.info}>{label[item.severity] ?? item.severity}</Badge><Badge variant="outline" className="border-white/10 text-zinc-400">Keyakinan {item.confidence === "high" ? "tinggi" : item.confidence === "medium" ? "sedang" : "rendah"}</Badge><span className="text-sm font-medium text-zinc-200">{item.title}</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{item.rationale}</p><p className="mt-2 text-xs leading-5 text-emerald-200">Remediasi: {item.remediation}</p></div>)}</div>}<p className="flex gap-2 text-xs leading-5 text-amber-200"><Sparkles className="mt-0.5 h-4 w-4 shrink-0" />{insight.caveat}</p></div> : <p className="text-xs text-zinc-500">Payload yang dikirim ke AI menghapus field credential, token, cookie, password, dan data personal sebelum dianalisis.</p>}</CardContent></Card>;
}
